name: mini_golf_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  flutter_login: any
  font_awesome_flutter: any
  flutter_gravatar: any
  transparent_image: any
  word_generator: any
  recase: any
  shared_preferences: any
  random_x: any
  uuid: any
  animated_background: any
  confetti: any
  intl: any
  holiday_event_api: any
  calendarific_dart: any
  cached_network_image: any
  supabase_flutter: any
  firebase_core: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

dependency_overrides:
  sign_in_with_apple: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
