// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
import 'package:flutter/foundation.dart' as foundation;

bool isWebTest = false;
bool get isWeb => isWebTest || foundation.kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (isWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb_YP2kMPuhxV531NJFMPfFoUKxlsaQi8',
    appId: '1:114725116317:web:0c58ae746a1956a8903774',
    messagingSenderId: '114725116317',
    projectId: 'mini-golf-tracker-dahome',
    authDomain: 'mini-golf-tracker-dahome.firebaseapp.com',
    storageBucket: 'mini-golf-tracker-dahome.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEydUasAiDm-RcK4nLYPWBCXcZomz8Eac',
    appId: '1:114725116317:android:299f9af42a67950a903774',
    messagingSenderId: '114725116317',
    projectId: 'mini-golf-tracker-dahome',
    storageBucket: 'mini-golf-tracker-dahome.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC108oyI_oyCAFPERH1DlXs_5xHF-g4kLw',
    appId: '1:114725116317:ios:61765a6d7b137631903774',
    messagingSenderId: '114725116317',
    projectId: 'mini-golf-tracker-dahome',
    storageBucket: 'mini-golf-tracker-dahome.firebasestorage.app',
    iosBundleId: 'com.example.miniGolfTracker',
  );
}
