name: Firebase App Distribution

on:
  push:
    branches:
      - master
      - main

jobs:
  build_and_distribute:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get

      - name: Calculate Semantic Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          
      - name: Tag new version
        run: |
          git tag v${{ steps.semver.outputs.version }}
          git push origin v${{ steps.semver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Debug Keystore Fingerprint
        run: |
          echo "### Keystore Fingerprint in GitHub Actions ###"
          keytool -list -v -keystore android/app/upload-keystore.jks -alias ${{ secrets.KEY_ALIAS }} -storepass ${{ secrets.KEYSTORE_PASSWORD }} | grep "SHA256:"

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF

      - name: Build App Bundle
        run: flutter build appbundle --build-name=${{ steps.semver.outputs.version }} --build-number=${{ github.run_number }}

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: '1:114725116317:android:299f9af42a67950a903774'
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/bundle/release/app-release.aab
